//
//  localization.js
//  CloseTabs
//
//  Created by Hiroyuki KITAGO on 2025/09/27.
//

const labelStrings = {
  "en": {
    "onError": "To use this extension, you need to have at least 2 tabs open. Open a new tab and try again.",
    "settings": "Settings",
    "settingsDone": "Done",
    "startpage": "Start Page",
    "settingsKeepActive": "Keep active tab",
    "settingsKeepPinned": "Keep pinned tabs",
    "closeTabsBtn": "Close Selected Tabs",
  },
  "ar": {
    "onError": "لاستخدام هذا الامتداد، يجب فتح علامتي تبويب على الأقل. افتح علامة تبويب جديدة وحاول مرة أخرى.",
    "settings": "الإعدادات",
    "settingsDone": "تم",
    "startpage": "صفحة البداية",
    "settingsKeepActive": "الاحتفاظ بعلامة التبويب النشطة",
    "settingsKeepPinned": "الاحتفاظ بعلامات التبويب المثبتة",
    "closeTabsBtn": "إغلاق علامات التبويب المحددة",
  },
  "ar-SA": {
    "onError": "لاستخدام هذا الامتداد، يجب فتح علامتي تبويب على الأقل. افتح علامة تبويب جديدة وحاول مرة أخرى.",
    "settings": "الإعدادات",
    "quoteStyleSetting": "اقتباس",
    "settingsDone": "تم",
    "startpage": "صفحة البداية",
    "settingsKeepActive": "الاحتفاظ بعلامة التبويب النشطة",
    "settingsKeepPinned": "الاحتفاظ بعلامات التبويب المثبتة",
    "closeTabsBtn": "إغلاق علامات التبويب المحددة",
  },
  "ca": {
    "onError": "Per utilitzar aquesta extensió, necessites tenir almenys 2 pestanyes obertes. Obre una pestanya nova i torna-ho a provar.",
    "settings": "Configuració",
    "settingsDone": "Fet",
    "startpage": "Pàgina d'inici",
    "settingsKeepActive": "Mantén la pestanya activa",
    "settingsKeepPinned": "Mantén les pestanyes fixades",
    "closeTabsBtn": "Tanca les pestanyes seleccionades",
  },
  "cs": {
    "onError": "Chcete-li použít toto rozšíření, musíte mít otevřené alespoň 2 karty. Otevřete novou kartu a zkuste to znovu.",
    "settings": "Nastavení",
    "settingsDone": "Hotovo",
    "startpage": "Úvodní stránka",
    "settingsKeepActive": "Ponechat aktivní kartu",
    "settingsKeepPinned": "Ponechat připnuté karty",
    "closeTabsBtn": "Zavřít vybrané karty",
  },
  "da": {
    "onError": "For at bruge denne udvidelse skal du have mindst 2 faner åbne. Åbn en ny fane, og prøv igen.",
    "settings": "Indstillinger",
    "settingsDone": "Færdig",
    "startpage": "Startside",
    "settingsKeepActive": "Behold aktiv fane",
    "settingsKeepPinned": "Behold fastgjorte faner",
    "closeTabsBtn": "Luk valgte faner",
  },
  "de": {
    "onError": "Um diese Erweiterung zu verwenden, müssen mindestens 2 Tabs geöffnet sein. Öffne einen neuen Tab und versuche es erneut.",
    "settings": "Einstellungen",
    "settingsDone": "Fertig",
    "startpage": "Startseite",
    "settingsKeepActive": "Aktiven Tab behalten",
    "settingsKeepPinned": "Angeheftete Tabs behalten",
    "closeTabsBtn": "Ausgewählte Tabs schließen",
  },
  "el": {
    "onError": "Για να χρησιμοποιήσετε αυτήν την επέκταση, πρέπει να έχετε ανοιχτές τουλάχιστον 2 καρτέλες. Ανοίξτε μια νέα καρτέλα και δοκιμάστε ξανά.",
    "settings": "Ρυθμίσεις",
    "settingsDone": "Έγινε",
    "startpage": "Αρχική σελίδα",
    "settingsKeepActive": "Διατήρηση ενεργής καρτέλας",
    "settingsKeepPinned": "Διατήρηση καρφιτσωμένων καρτελών",
    "closeTabsBtn": "Κλείσιμο επιλεγμένων καρτελών",
  },
  "en-GB": {
    "onError": "To use this extension, you need to have at least 2 tabs open. Open a new tab and try again.",
    "settings": "Settings",
    "settingsDone": "Done",
    "startpage": "Start Page",
    "settingsKeepActive": "Keep active tab",
    "settingsKeepPinned": "Keep pinned tabs",
    "closeTabsBtn": "Close Selected Tabs",
  },
  "en-AU": {
    "onError": "To use this extension, you need to have at least 2 tabs open. Open a new tab and try again.",
    "settings": "Settings",
    "settingsDone": "Done",
    "startpage": "Start Page",
    "settingsKeepActive": "Keep active tab",
    "settingsKeepPinned": "Keep pinned tabs",
    "closeTabsBtn": "Close Selected Tabs",
  },
  "en-CA": {
    "onError": "To use this extension, you need to have at least 2 tabs open. Open a new tab and try again.",
    "settings": "Settings",
    "settingsDone": "Done",
    "startpage": "Start Page",
    "settingsKeepActive": "Keep active tab",
    "settingsKeepPinned": "Keep pinned tabs",
    "closeTabsBtn": "Close Selected Tabs",
  },
  "es": {
    "onError": "Para usar esta extensión, debes tener al menos 2 pestañas abiertas. Abre una pestaña nueva e inténtalo de nuevo.",
    "settings": "Configuración",
    "settingsDone": "Hecho",
    "startpage": "Página de inicio",
    "settingsKeepActive": "Mantener pestaña activa",
    "settingsKeepPinned": "Mantener pestañas fijadas",
    "closeTabsBtn": "Cerrar pestañas seleccionadas",
  },
  "es-MX": {
    "onError": "Para usar esta extensión, debes tener al menos 2 pestañas abiertas. Abre una pestaña nueva e inténtalo de nuevo.",
    "settings": "Configuración",
    "settingsDone": "Hecho",
    "startpage": "Página de inicio",
    "settingsKeepActive": "Mantener pestaña activa",
    "settingsKeepPinned": "Mantener pestañas fijadas",
    "closeTabsBtn": "Cerrar pestañas seleccionadas",
  },
  "fi": {
    "onError": "Jotta voit käyttää tätä laajennusta, sinulla on oltava vähintään 2 välilehteä auki. Avaa uusi välilehti ja yritä uudelleen.",
    "settings": "Asetukset",
    "settingsDone": "Valmis",
    "startpage": "Aloitussivu",
    "settingsKeepActive": "Säilytä aktiivinen välilehti",
    "settingsKeepPinned": "Säilytä kiinnitetyt välilehdet",
    "closeTabsBtn": "Sulje valitut välilehdet",
  },
  "fr": {
    "onError": "Pour utiliser cette extension, vous devez avoir au moins 2 onglets ouverts. Ouvrez un nouvel onglet et réessayez.",
    "settings": "Réglages",
    "settingsDone": "Terminé",
    "startpage": "Page de démarrage",
    "settingsKeepActive": "Conserver l'onglet actif",
    "settingsKeepPinned": "Conserver les onglets épinglés",
    "closeTabsBtn": "Fermer les onglets sélectionnés",
  },
  "fr-CA": {
    "onError": "Pour utiliser cette extension, vous devez avoir au moins 2 onglets ouverts. Ouvrez un nouvel onglet et réessayez.",
    "settings": "Réglages",
    "settingsDone": "Terminé",
    "startpage": "Page de démarrage",
    "settingsKeepActive": "Conserver l'onglet actif",
    "settingsKeepPinned": "Conserver les onglets épinglés",
    "closeTabsBtn": "Fermer les onglets sélectionnés",
  },
  "hu": {
    "onError": "A bővítmény használatához legalább 2 lapot kell megnyitni. Nyiss meg egy új lapot, és próbáld újra.",
    "settings": "Beállítások",
    "settingsDone": "Kész",
    "startpage": "Kezdőoldal",
    "settingsKeepActive": "Aktív lap megtartása",
    "settingsKeepPinned": "Rögzített lapok megtartása",
    "closeTabsBtn": "Kijelölt fülek bezárása",
  },
  "he": {
    "onError": "כדי להשתמש בהרחבה זו, עליך לפתוח לפחות 2 כרטיסיות. פתח כרטיסייה חדשה ונסה שוב.",
    "settings": "הגדרות",
    "settingsDone": "סיים",
    "startpage": "דף התחלה",
    "settingsKeepActive": "שמור כרטיסייה פעילה",
    "settingsKeepPinned": "שמור כרטיסיות נעוצות",
    "closeTabsBtn": "סגור כרטיסיות נבחרות",
  },
  "hr": {
    "onError": "Za upotrebu ovog proširenja morate imati otvorene najmanje 2 kartice. Otvorite novu karticu i pokušajte ponovo.",
    "settings": "Postavke",
    "settingsDone": "Gotovo",
    "startpage": "Početna stranica",
    "settingsKeepActive": "Zadrži aktivnu karticu",
    "settingsKeepPinned": "Zadrži pričvršćene kartice",
    "closeTabsBtn": "Zatvori odabrane kartice",
  },
  "hi": {
    "onError": "इस एक्सटेंशन का उपयोग करने के लिए, आपको कम से कम 2 टैब खोलने होंगे। एक नया टैब खोलें और पुनः प्रयास करें।",
    "settings": "सेटिंग्स",
    "settingsDone": "पूर्ण",
    "startpage": "प्रारंभ पृष्ठ",
    "settingsKeepActive": "सक्रिय टैब रखें",
    "settingsKeepPinned": "पिन किए गए टैब रखें",
    "closeTabsBtn": "चयनित टैब बंद करें",
  },
  "id": {
    "onError": "Untuk menggunakan ekstensi ini, Anda harus membuka setidaknya 2 tab. Buka tab baru dan coba lagi.",
    "settings": "Pengaturan",
    "settingsDone": "Selesai",
    "startpage": "Halaman Awal",
    "settingsKeepActive": "Simpan Tab Aktif",
    "settingsKeepPinned": "Simpan Tab yang Disematkan",
    "closeTabsBtn": "Tutup Tab yang Dipilih",
  },
  "it": {
    "onError": "Per utilizzare questa estensione, devi avere almeno 2 pannelli aperti. Apri un nuovo pannello e riprova.",
    "settings": "Impostazioni",
    "settingsDone": "Fatto",
    "startpage": "Pagina iniziale",
    "settingsKeepActive": "Mantieni pannello attivo",
    "settingsKeepPinned": "Mantieni pannelli bloccati",
    "closeTabsBtn": "Chiudi pannelli selezionati",
  },
  "ja": {
    "onError": "この機能拡張を使用するには、2つ以上のタブを開く必要があります。新しいタブを開いてから、もう一度お試しください。",
    "settings": "設定",
    "settingsDone": "完了",
    "startpage": "スタートページ",
    "settingsKeepActive": "表示中のタブを残す",
    "settingsKeepPinned": "固定したタブを残す",
    "closeTabsBtn": "選択したタブを閉じる",
  },
  "ko-KR": {
    "onError": "이 확장 프로그램을 사용하려면 최소 2개의 탭이 열려 있어야 합니다. 새 탭을 열고 다시 시도하십시오.",
    "settings": "설정",
    "settingsDone": "완료",
    "startpage": "시작 페이지",
    "settingsKeepActive": "활성 탭 유지",
    "settingsKeepPinned": "고정된 탭 유지",
    "closeTabsBtn": "선택한 탭 닫기",
  },
  "ms": {
    "onError": "Untuk menggunakan sambungan ini, anda perlu membuka sekurang-kurangnya 2 tab. Buka tab baharu dan cuba lagi.",
    "settings": "Tetapan",
    "settingsDone": "Selesai",
    "startpage": "Halaman Mula",
    "settingsKeepActive": "Simpan Tab Aktif",
    "settingsKeepPinned": "Simpan Tab Disemat",
    "closeTabsBtn": "Tutup Tab Terpilih",
  },
  "nb": {
    "onError": "For å bruke denne utvidelsen må du ha minst 2 faner åpne. Åpne en ny fane og prøv på nytt.",
    "settings": "Innstillinger",
    "settingsDone": "Ferdig",
    "startpage": "Startside",
    "settingsKeepActive": "Behold aktiv fane",
    "settingsKeepPinned": "Behold festede faner",
    "closeTabsBtn": "Lukk valgte faner",
  },
  "nl": {
    "onError": "Om deze extensie te gebruiken moet je minstens 2 tabbladen geopend hebben. Open een nieuw tabblad en probeer het opnieuw.",
    "settings": "Instellingen",
    "settingsDone": "Klaar",
    "startpage": "Startpagina",
    "settingsKeepActive": "Actief tabblad behouden",
    "settingsKeepPinned": "Vastgemaakte tabbladen behouden",
    "closeTabsBtn": "Sluit geselecteerde tabbladen",
  },
  "pl": {
    "onError": "Aby korzystać z tego rozszerzenia, musisz mieć otwarte co najmniej 2 karty. Otwórz nową kartę i spróbuj ponownie.",
    "settings": "Ustawienia",
    "settingsDone": "Gotowe",
    "startpage": "Strona startowa",
    "settingsKeepActive": "Zachowaj aktywną kartę",
    "settingsKeepPinned": "Zachowaj przypięte karty",
    "closeTabsBtn": "Zamknij wybrane karty",
  },
  "pt": {
    "onError": "Para usar esta extensão, você precisa ter pelo menos 2 abas abertas. Abra uma nova aba e tente novamente.",
    "settings": "Configurações",
    "settingsDone": "Concluído",
    "startpage": "Página inicial",
    "settingsKeepActive": "Manter aba ativa",
    "settingsKeepPinned": "Manter abas fixadas",
    "closeTabsBtn": "Fechar abas selecionadas",
  },
  "pt-PT": {
    "onError": "Para utilizar esta extensão, tem de ter pelo menos 2 separadores abertos. Abra um novo separador e tente novamente.",
    "settings": "Definições",
    "settingsDone": "Concluído",
    "startpage": "Página inicial",
    "settingsKeepActive": "Manter separador ativo",
    "settingsKeepPinned": "Manter separadores afixados",
    "closeTabsBtn": "Fechar separadores selecionados",
  },
  "pt-BR": {
    "onError": "Para usar esta extensão, você precisa ter pelo menos 2 abas abertas. Abra uma nova aba e tente novamente.",
    "settings": "Configurações",
    "settingsDone": "Concluído",
    "startpage": "Página inicial",
    "settingsKeepActive": "Manter aba ativa",
    "settingsKeepPinned": "Manter abas fixadas",
    "closeTabsBtn": "Fechar abas selecionadas",
  },
  "ro": {
    "onError": "Pentru a folosi această extensie, trebuie să aveți deschise cel puțin 2 file. Deschideți o filă nouă și încercați din nou.",
    "settings": "Setări",
    "settingsDone": "Finalizat",
    "startpage": "Pagina de pornire",
    "settingsKeepActive": "Păstrează fila activă",
    "settingsKeepPinned": "Păstrează filele fixate",
    "closeTabsBtn": "Închide filele selectate",
  },
  "ru": {
    "onError": "Чтобы использовать это расширение, необходимо открыть как минимум 2 вкладки. Откройте новую вкладку и повторите попытку.",
    "settings": "Настройки",
    "settingsDone": "Готово",
    "startpage": "Стартовая страница",
    "settingsKeepActive": "Сохранить активную вкладку",
    "settingsKeepPinned": "Сохранить закрепленные вкладки",
    "closeTabsBtn": "Закрыть выбранные вкладки",
  },
  "sk": {
    "onError": "Ak chcete použiť toto rozšírenie, musíte mať otvorené aspoň 2 karty. Otvorte novú kartu a skúste to znova.",
    "settings": "Nastavenia",
    "settingsDone": "Hotovo",
    "startpage": "Úvodná stránka",
    "settingsKeepActive": "Ponechať aktívnu kartu",
    "settingsKeepPinned": "Ponechať pripnuté karty",
    "closeTabsBtn": "Close Selected Tabs",
  },
  "sv": {
    "onError": "För att använda detta tillägg måste du ha minst 2 flikar öppna. Öppna en ny flik och försök igen.",
    "settings": "Inställningar",
    "settingsDone": "Klar",
    "startpage": "Startsida",
    "settingsKeepActive": "Behåll aktiv flik",
    "settingsKeepPinned": "Behåll fästa flikar",
    "closeTabsBtn": "Zavrieť vybraté karty",
  },
  "th": {
    "onError": "หากต้องการใช้ส่วนขยายนี้ คุณต้องเปิดแท็บอย่างน้อย 2 แท็บ เปิดแท็บใหม่และลองอีกครั้ง",
    "settings": "การตั้งค่า",
    "settingsDone": "เสร็จสิ้น",
    "startpage": "หน้าเริ่มต้น",
    "settingsKeepActive": "เก็บแท็บที่ใช้งานอยู่",
    "settingsKeepPinned": "เก็บแท็บที่ปักหมุด",
    "closeTabsBtn": "ปิดแท็บที่เลือก",
  },
  "tr": {
    "onError": "Bu uzantıyı kullanmak için en az 2 sekme açık olmalıdır. Yeni bir sekme açın ve tekrar deneyin.",
    "settings": "Ayarlar",
    "settingsDone": "Tamam",
    "startpage": "Başlangıç Sayfası",
    "settingsKeepActive": "Etkin Sekmeyi Tut",
    "settingsKeepPinned": "Sabitlenmiş Sekmeleri Tut",
    "closeTabsBtn": "Seçili Sekmeleri Kapat",
  },
  "uk": {
    "onError": "Щоб використовувати це розширення, необхідно відкрити принаймні 2 вкладки. Відкрийте нову вкладку та повторіть спробу.",
    "settings": "Налаштування",
    "settingsDone": "Готово",
    "startpage": "Початкова сторінка",
    "settingsKeepActive": "Зберегти активну вкладку",
    "settingsKeepPinned": "Зберегти закріплені вкладки",
    "closeTabsBtn": "Закрити вибрані вкладки",
  },
  "vi": {
    "onError": "Để sử dụng tiện ích này, bạn cần mở ít nhất 2 tab. Hãy mở tab mới và thử lại.",
    "settings": "Cài đặt",
    "settingsDone": "Xong",
    "startpage": "Trang bắt đầu",
    "settingsKeepActive": "Giữ tab đang hoạt động",
    "settingsKeepPinned": "Giữ các tab đã ghim",
    "closeTabsBtn": "Đóng các tab đã chọn",
  },
  "zh": {
    "onError": "要使用此扩展,您需要打开至少 2 个标签页。请打开一个新标签页,然后重试。",
    "settings": "设置",
    "settingsDone": "完成",
    "startpage": "起始页",
    "settingsKeepActive": "保留活跃标签页",
    "settingsKeepPinned": "保留固定标签页",
    "closeTabsBtn": "关闭所选标签页",
  },
  "zh-CN": {
    "onError": "要使用此扩展,您需要打开至少 2 个标签页。请打开一个新标签页,然后重试。",
    "settings": "设置",
    "settingsDone": "完成",
    "startpage": "起始页",
    "settingsKeepActive": "保留活跃标签页",
    "settingsKeepPinned": "保留固定标签页",
    "closeTabsBtn": "关闭所选标签页",
  },
  "zh-TW": {
    "onError": "若要使用此功能擴充,您需要開啟至少 2 個分頁。請開啟新分頁,然後再試一次。",
    "settings": "設定",
    "settingsDone": "完成",
    "startpage": "起始頁面",
    "settingsKeepActive": "保留使用中分頁",
    "settingsKeepPinned": "保留已釘選分頁",
    "closeTabsBtn": "關閉所選分頁",
  },
  "zh-HK": {
    "onError": "若要使用此功能擴充,您需要開啟至少 2 個分頁。請開啟新分頁,然後再試一次。",
    "settings": "設定",
    "settingsDone": "完成",
    "startpage": "起始頁面",
    "settingsKeepActive": "保留使用中分頁",
    "settingsKeepPinned": "保留已釘選分頁",
    "closeTabsBtn": "關閉所選分頁",
  },
};

export const getCurrentLangLabelString = (key = 'onError') => {
  const langCode = window.navigator.language || 'en';
  const baseLang = langCode.split('-')[0];

  return (
    labelStrings[langCode]?.[key] ??
    labelStrings[baseLang]?.[key] ??
    labelStrings.en[key]
  );
};

export const applyRTLSupport = () => {
  const langCode = window.navigator.language || 'en';
  const baseLang = langCode.split('-')[0];

  if (baseLang === 'ar' || baseLang === 'he') {
    document.body.classList.add('rtl');
    document.documentElement.setAttribute('lang', baseLang);
    document.documentElement.setAttribute('dir', 'rtl');
  } else {
    document.body.classList.remove('rtl');
    document.documentElement.removeAttribute('dir');
  }
};
